### ISSUE TITLE
Possibly gratuitous test

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#12]
Is this test needed?
      self.assertEqual( sample_output.shape[1], sample_input.shape[1] )
Isn't this covered by not having extra columns/not having missing columns?

**Comment by tatiana-boura** [comment]
Yes, this is needed. I explain it in the comment in line 98 of file ```test_preprocessing.py``` (commit 4be2cd0122251a594b948bfb7f8e0de88f3feab6).
