### ISSUE TITLE
Uncaught timeout exception

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#16]
The InfluxDB client threw `urllib3.exceptions.ReadTimeoutError` for some time, then the server became responsive again. Probably not a network error, as the host was pingable at the time.

Regardless of any relevant work or update at the server side, the clinet should not terminate but catch the exception, wait, and re-try. Also, care should be taken to isolate PLC reading from exceptions in the network access. Probably a separate process or a catch-all exception catch that logs errors but does not terminate the process.

**Comment by tatiana-boura** [comment]
Regarding the ```urllib3.exceptions.ReadTimeoutError```: this type of error can be raised from the ```influx.py``` functions in the ```navgreen_base``` module. From what I gather, the modifications should be made to the respective functions : _connect_, _write_, _read_ and _delete_.

**Comment by stasinos** [comment]
I am not sure, as this would spread the catching and logging of these exceptions all over the place. Also consider how the historical data analysis application can throw exceptions with no harm done.

It seems that wrapping the relevant parts of the live data ingestion application around try-catch clauses would be the minimal-change approach to ensuring exceptions do not lead to data loss.

Exceptions should be logged. We can printf for now and move to a formal logging framework later or use a logger already, your call.

**Comment by tatiana-boura** [comment]
I am thinking of using Python's default  [logging](https://docs.python.org/3.12/library/logging.html). Any comments or suggestions?

**Comment by stasinos** [comment]
Looks familiar from other languages, should be fine.

**Comment by tatiana-boura** [comment]
I'd like to mention (for logging purposes) that this issue also involves ensuring that, even in the event of connection problems with InfluxDB, we don't lose the data being read from the PLC.
