### ISSUE TITLE
Use the new pre-processing and logging infrastructure

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#18]
To avoid rebasing or complex merges, and since this will be straightforward, PR #17 does not merge the pre-processing and logging infrastructure from Issue #8 before closing Issue #1 

This issue will do just this.

**Comment by tatiana-boura** [comment]
This issue will implement the new preprocessing infrastructure.

The logging infrastructure will be applied in Issue #22, as Issue #16 needs to be resolved first before doing so.
