### ISSUE TITLE
Read and store checkpoints from live data

### ISSUE THREAD

**Issue by tatiana-boura** [data-eng/navgreen#20]
Currently, in live data analysis, we only read the `checkpoints` but do not store them. This functionality needs to be implemented, and a few considerations should be taken into account:

1. As this type of data changes sparsely, the corresponding value should be stored only when it changes to avoid storing redundant data.
2. We should also consider the representation of the checkpoints to assess their similarity with previous values.

**Comment by tatiana-boura** [comment]
The checkpoints represent temperature values that define the desired temperature range for the corresponding container. For instance, if the checkpoint is 42.0, then the temperature  $t \in[42.0 - \delta, 42.0 + \delta ]$ for some $\delta \geq 0$. Currently, the configured $\delta$ is set to 5.

@ge0rgemera highlighted that when adjusting the checkpoints, they typically modify the integer part of the float and very rarely alter the first decimal. Therefore, we should focus on storing checkpoint values that adhere to these patterns.

**Comment by tatiana-boura** [comment]
This Issue is to be fixed by PR #33, but it should be revisited when we develop code that remotely changes the values of the checkpoints.

**Comment by stasinos** [comment]
Is there an issue outlining what should be checked or changed when that code is developed?

**Comment by tatiana-boura** [comment]
I was thinking that we could create it once we agree on the structure of the code in Issue #30.

**Comment by stasinos** [comment]
Added a relevant comment in #30
