### ISSUE TITLE
flow_condenser prepocessing

### ISSUE THREAD

**Issue by tatiana-boura** [data-eng/navgreen#28]
The PLC reads and stores the flow values as positive integers that we then use as floating points (dividing them by 10). However, the ```flow_condenser``` measurement may take negative values when the heat pump is not working, leading to numerical underflow. Therefore, we should fix this issue:  

- (Temporarily) by clipping all values greater than 4
- (Permanently) by reading the correct variable type

**Comment by tatiana-boura** [comment]
We should also update the testcase with this new limit by:

1. Injecting artificial outliers
2. Updating the ```sample_output.csv```

**Comment by tatiana-boura** [comment]
This Issue is to be fixed by #33, but it should be revisited when we opt for the **permanent** fix.

**Comment by stasinos** [comment]
Is there an issue outlining the permanent fix?

**Comment by tatiana-boura** [comment]
I am awaiting @ge0rgemera's response about his observations, since he was the one who initially noticed the problem, in order to create the corresponding Issue.

**Comment by tatiana-boura** [comment]
Please @stasinos take a look at Issue #34 and add whatever other solution you might think of.
