### ISSUE TITLE
Read signed integers from PLC

### ISSUE THREAD

**Issue by tatiana-boura** [data-eng/navgreen#34]
By observing the values of the measurements in the PLC we concluded that some of them may take slightly negative values, even though they should not, due to some malfunction of the sensors.

As hinted by @ge0rgemera and highlighted in Issue #28, the current code for reading the measurements interprets unsigned integers from the PLC, causing the aforementioned negative values to be treated as large positives (numerical underflow).

This can be fixed, naively, by clipping the "large" values of the measurements, which we currently do. However, this approach requires domain-specific knowledge and remains prone to errors.

A more permanent solution would involve studying the documentation of the corresponding Python library used as an 'API' to identify any commands that read the signed version of the variable. If unsuccessful, we may need to wear our "programmer hat" and  manage the bitwise representation of the variables themselves and perform the sign translation manually.

**Comment by tatiana-boura** [comment]
How is the Issue #11 relevant?

**Comment by stasinos** [comment]
It is, indeed, bizarre noting how hard it is to mistype 11 when meaning to type Issue #28 
I think it is time for a short break

**Comment by tatiana-boura** [comment]
After some research, it looks like the Python library reads the raw 16-bit number, which is then interpreted as an unsigned integer. Therefore, the methodology implemented in the branch [signed-ints-from-live-data](https://github.com/data-eng/navgreen/tree/signed-ints-from-live-data) involves reading the number and then converting its bitwise representation to a signed integer. This approach is currently being tested at the installation.
