### ISSUE TITLE
Diffuse radiation

### ISSUE THREAD

**Issue by tatiana-boura** [data-eng/navgreen#39]
We should add another measurement, the diffuse radiation, that comes from another data-logger (not the PLC):

1. Read it from the live data
2. Store it to the .csv
3. See how it affects preprocessing and the testcases

**Comment by tatiana-boura** [comment]
@stasinos, branch [diffuse-solar-addition](https://github.com/data-eng/navgreen/tree/diffuse-solar-addition) encorporates the diffuse solar radiation value from a different source (other than the PLC). 

How do you reckon we should proceed with the testing? Leave it as it is: only test the writing and reading of the historical data?
Or somehow add the diffuse to the equation, which we only today started reading and storing?

**Comment by stasinos** [comment]
I think we should leave it as it is for now, and open a new ticket to re-visit the live-data test cases after we have observed failures and now what to test for.
