### ISSUE TITLE
Filter out outliers

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#4]
See if we can set guaranteed limits on the range of values or the range of rate of change of values for each sensor.
See for instance:

> df.iloc[259492:259498]["INDOOR_TEMP"]
259492     20.2
259493     20.3
259494   -207.0
259495   -115.8
259496     21.0
259497     20.6

**Comment by stasinos** [comment]
Based on information provided by @ge0rgemera:

- Temperatures should be between -20 and 100
- Pressures should be between 0 and 35 bar
- Values after Aug 2022 are more reliable
- Indoor temperatures values after 6 Dec 2022 are considerable more reliable

**Comment by tatiana-boura** [comment]
Adding to the above information (also provided by @ge0rgemera):

- The solar sensor's values should be between 0 and 2. However, the solar sensor seems to malfunction at night and gather solar energy greater than 2.0. To address this issue, if solar energy exceeds 2.0, then its value is trimmed to 0.0.
