### ISSUE TITLE
Create a testcase for live data ingestion

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#6]
To be able to test changes in the live data ingestion code, prepare a sample of really-raw live data, a test bucket, and a query that pulls all of this data in a CVS, and a "golden" CSV. Testing should:

- wipe clean the test bucket
- process the raw data sample and write to the bucket
- execute the query
- compare the query result with the golden CSV

**Comment by tatiana-boura** [comment]
Please review commit 6eb9f67c59b9a57d6866572a251c373cdf8ec40d, which accomplishes the aforementioned tasks. It was tested today and "works like a charm".

If this test case is deemed sufficient, we can consider this issue as closed.

**Comment by stasinos** [comment]
I created two new pointers:
 - ingest-live-data points to the last commit in the current development branch before starting to work on the testcase
 - ingest-live-data-testcase points to the commit you give above, and should track work on the testcase

When work on the testcase is finished, please open a PR to merge ingest-live-data-testcase into ingest-live-data.

**Comment by stasinos** [comment]
To have a testcase we need:
- Sample input: A sample of really-raw live data. This can be a CSV or a JSON, as per your convenience.
- Sample output: The same data after preprocessing, loading into the bucket, and querying it back.
- A script that wipes clean a test bucket, reads the sample, applies all filtering and preprocessing, and loads the data into the test bucket. The script MUST import the preprocessing code from the ingestion script, rather than repeat it, so that it tests the actual code used on the live system.
- The script must then query the test bucket, load the sample output, compare the two, and report any differences.

Naturally, we do not have a sample output at this stage. So we will assume that the current implementation is correct and use to create a sample output. The testcase will serve to protect us against regressing in future changes.

The sample input and sample output should be committed, let us call the directory test/
They do not need to be large, but they need to be characteristic of possible corner cases:
- At least one NaN value
- At least one outlier value
We can expand in the future as we come across problems, and update the testcase accordingly.

The bucket name and creds MUST NOT be committed but be read from env variables.

**Comment by stasinos** [comment]
The testcase will be updated as we observe outliers and corner cases, but is complete as per our current understanding
